mwssro_prod/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteSericeProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','Auth\LoginController@showLoginForm');
Auth::routes();

Route::group(['middleware' => 'auth'],function(){

	Route::resource('dashboards', 'DashboardsController');


	Route::group(['prefix' => 'payrolls/admin/filemanagers'],function(){

		Route::get('benefits/getItem','BenefitsController@getItem');
		Route::resource('benefits','BenefitsController');

		Route::get('adjustments/getItem','AdjustmentsController@getItem');
		Route::resource('adjustments','AdjustmentsController');

		Route::get('deductions/getItem','DeductionsController@getItem');
		Route::resource('deductions','DeductionsController');

		Route::get('loans/getItem','LoansController@getItem');
		Route::resource('loans','LoansController');

		Route::get('responsibilitiescenter/getItem','ResponsibilitiesCenterController@getItem');
		Route::resource('responsibilitiescenter','ResponsibilitiesCenterController');

		Route::get('banks/getItem','BanksController@getItem');
		Route::resource('banks','BanksController');

		Route::get('bankbranches/getItem','BankBranchesController@getItem');
		Route::resource('bankbranches','BankBranchesController');

		Route::post('pagibig/storePolicy','PagibigController@storePolicy');
		Route::get('pagibig/showPolicy','PagibigController@showPolicy');
		Route::get('pagibig/getItem','PagibigController@getItem');
		Route::resource('pagibig','PagibigController');

		Route::post('philhealths/storePolicy','PhilhealthsController@storePolicy');
		Route::get('philhealths/showPolicy','PhilhealthsController@showPolicy');
		Route::get('philhealths/getItem','PhilhealthsController@getItem');
		Route::resource('philhealths','PhilhealthsController');

		Route::get('providentfundpolicies/getItem','ProvidentFundPoliciesController@getItem');
		Route::resource('providentfundpolicies','ProvidentFundPoliciesController');

		Route::get('salariesgrade/getSgstep','SalariesGradeController@getSgstep');
		Route::resource('salariesgrade','SalariesGradeController');

		Route::post('taxes/storeTaxstatus','TaxesController@storeTaxstatus');
		Route::get('taxes/showTaxstatus','TaxesController@showTaxstatus');
		Route::post('taxes/storeTaxstatusannual','TaxesController@storeTaxstatusannual');
		Route::get('taxes/showTaxstatusannual','TaxesController@showTaxstatusannual');
		Route::post('taxes/storeTaxpolicy','TaxesController@storeTaxpolicy');
		Route::post('taxes/deleteTaxPolicy','TaxesController@deleteTaxPolicy');
		Route::get('taxes/showTaxpolicy','TaxesController@showTaxpolicy');

		Route::get('taxes/getTaxtable','TaxesController@getTaxtable');
		Route::get('taxes/getTaxstatus','TaxesController@getTaxstatus');
		Route::get('taxes/getTaxannual','TaxesController@getTaxannual');
		Route::get('taxes/getTaxpolicy','TaxesController@getTaxpolicy');

		Route::resource('taxes','TaxesController');

		Route::get('wagerates/getItem','WageRatesController@getItem');
		Route::resource('wagerates','WageRatesController');

		Route::get('gsis/getItem','GsisController@getItem');
		Route::resource('gsis','GsisController');

		Route::get('jobgrades/getJgstep','GsisController@getJgstep');
		Route::resource('jobgrades','JobGradesController');

		Route::resource('divisions','DivisionsController');
		Route::resource('offices','OfficesController');
		Route::resource('employeestatus','EmployeeStatusController');
		Route::resource('positions','PositionsController');
		Route::resource('position_items','PositionItemsController');
		Route::resource('rates','RatesController');
		Route::resource('travelrates','TravelRateController');
		Route::resource('series_codes','SeriesCodeController');
	});

	Route::group(['prefix' => 'payrolls/reports/remittances'],function(){
		Route::get('gsis/getEmployeeinfo','GsisRemittancesController@getEmployeeinfo');
		Route::resource('gsis','GsisRemittancesController');
		Route::get('ecip/getEmployeeinfo','EcipRemittancesController@getEmployeeinfo');
		Route::resource('ecip','EcipRemittancesController');
		Route::get('pagibig/getEmployeeinfo','PagibigRemittancesController@getEmployeeinfo');
		Route::resource('pagibig','PagibigRemittancesController');
		Route::get('philhealth/getEmployeeinfo','PhilhealthRemittancesController@getEmployeeinfo');
		Route::resource('philhealth','PhilhealthRemittancesController');
	});

	Route::group(['prefix' => 'payrolls/reports/othercompensations'],function(){

		Route::get('communicationexpense/getEmployeeinfo','CommunicationExpenseReportController@getEmployeeinfo');
		Route::resource('communicationexpense','CommunicationExpenseReportController');

		Route::get('eme/getEmployeeinfo','EmeReportsController@getEmployeeinfo');
		Route::resource('eme','EmeReportsController');

		Route::get('cashmidyearbonus/getEmployeeinfo','CashGiftsAndMidYearReportController@getEmployeeinfo');
		Route::resource('cashmidyearbonus','CashGiftsAndMidYearReportController');
	});

	Route::group(['prefix' => 'payrolls/reports/nonplantillareports'], function(){

		Route::get('cocpayrollworksheets/getPayrollWorksheetReport','COCPayrollWorksheetReportController@getPayrollWorksheetReport');
		Route::post('cocpayrollworksheets/postReport','COCPayrollWorksheetReportController@postReport');
		Route::resource('cocpayrollworksheets','COCPayrollWorksheetReportController');

		Route::get('cocgeneralpayroll/getGeneralPayrollReport','COCGeneralPayrollReportController@getGeneralPayrollReport');
		Route::post('cocgeneralpayroll/postReport','COCGeneralPayrollReportController@postReport');
		Route::resource('cocgeneralpayroll','COCGeneralPayrollReportController');
		Route::resource('costransmital','COSTransmitalReportsController');

	});

	Route::group(['prefix'=>'payrolls/reports/plantillareports'],function(){
		Route::post('payrollworksheets/postReport','PayrollWorksheetReportController@postReport');
		Route::get('payrollworksheets/getPayrollWorksheetReport','PayrollWorksheetReportController@getPayrollWorksheetReport');
		Route::resource('payrollworksheets','PayrollWorksheetReportController');

		Route::post('generalpayroll/generateCSV','GeneralPayrollReportsController@generateCSV');
		Route::post('generalpayroll/postReport','GeneralPayrollReportsController@postReport');
		Route::resource('generalpayroll','GeneralPayrollReportsController');
		Route::resource('regulartransmital','RegularTransmitalReportsController');
	});

	Route::group(['prefix'=>'payrolls/reports/overtimereports'],function(){

		Route::resource('overtimetransmital','OvertimeTransmitalReportsController');

		Route::post('generalpayrollovertime/postReport','GeneralPayrollOvertimeReportsController@postReport');
		Route::resource('generalpayrollovertime','GeneralPayrollOvertimeReportsController');

		Route::post('overtimepayrollworksheet/postReport','OvertimePayrollWorksheetReportsController@postReport');
		Route::resource('overtimepayrollworksheet','OvertimePayrollWorksheetReportsController');

	});

	Route::group(['prefix'=>'payrolls/reports/ratareports'],function(){

		Route::post('ratageneralpayroll/generateCSV','RataReportsController@generateCSV');

		Route::post('ratageneralpayroll/postReport','RataReportsController@postReport');
		Route::resource('ratageneralpayroll','RataReportsController');

		Route::post('ratapayrollworksheets/postReport','RataPayrollWorksheetReportsController@postReport');
		Route::resource('ratapayrollworksheets','RataPayrollWorksheetReportsController');
		Route::resource('ratatransmital','RataTransmitalReportsController');

	});
	Route::group(['prefix'=>'payrolls/reports/midyearreports'],function(){

		Route::resource('midyeargeneralpayroll','MidYearGeneralPayrollReportsReportsController');
		Route::resource('midyeartransmital','MidYearTransmitalReportsReportsController');

	});

	Route::group(['prefix'=>'payrolls/reports/yearendreports'],function(){

		Route::resource('yearendgeneralpayroll','YearEndGeneralPayrollReportsReportsController');
		Route::resource('yearendtransmital','YearEndTransmitalReportsReportsController');

	});

	Route::group(['prefix'=>'payrolls/reports/monetizationreports'],function(){

		Route::resource('monetizationgeneralpayroll','MonetizationGeneralPayrollReportsReportsController');
		Route::resource('monetizationtransmital','MonetizationTransmitalReportsReportsController');

	});

	Route::group(['prefix'=>'payrolls/reports/cnapeireports'],function(){
		Route::resource('cnapeigeneralpayroll','CNAPEIReportsController');
		Route::resource('cnapeitransmital','CNAPEITransmitalReportsController');
	});

	Route::group(['prefix' => 'payrolls/reports/honorariareports'],function(){
		Route::resource('generalpayrollhonoraria','GeneralPayrollHonorariaReportsController');
		Route::resource('honorariatransmital','TransmitalHonorariaReportsController');
	});

	Route::group(['prefix'=>'payrolls/reports'],function(){
		Route::get('payslips/getSearchby','PayslipsController@getSearchby');
		Route::get('payslips/getPayslip','PayslipsController@getPayslip');
		Route::post('payslips/postReport','PayslipsController@postReport');
		Route::resource('payslips','PayslipsController');

		Route::resource('multipurposeloans','MultiPurposeLoanReportsController');
		Route::resource('taxesremittance','TaxesRemittanceReportsController');
		Route::resource('ssscontributions','SSSContributionReportsController');
		Route::resource('mwsscooperative','MultiPurposeCooperativeReportsController');
		Route::resource('welfarefund','WelfareFundReportsController');
		Route::resource('mwsstubig','MultiPurposeTubigReportsController');
		Route::resource('serviceloans','ServiceLoanReportsController');
		Route::resource('premiumcontributions','PremiumContributionReportsController');

mwssro_prod/app/SeriesCode.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SeriesCode extends Model
{

    protected $primaryKey = 'id';
    protected $table  	  = 'pms_series_codes';

    protected $fillable = [

    	'code',
    	'description',
    	'created_by',
    	'updated_by'
    	
    ];
}

mwssro_prod/app/Http/Controllers/FileManagersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FileManagersController extends Controller
{
    
    function __construct(){
    	$this->module_prefix = 'payrolls';
    	$this->module = 'filemanagers';
    	$this->title = 'FILE MANAGER';
    	$this->controller = $this;
    }

    public function index(){

    	$response = array(
    					'module' => $this->module,
    					'module_prefix' => $this->module_prefix,
    					'title'			=> $this->title,
    					'controller'	=> $this->controller, 
    				);
        
    	return view($this->module_prefix.'.'.$this->module.'.index',$response);
    }
}

mwssro_prod/app/Http/Controllers/SeriesCodeController.php
<?php

namespace App\Http\Controllers;

use App\SeriesCode;
use Illuminate\Http\Request;

use Auth;
use Input;

class SeriesCodeController extends Controller
{

    function __construct(){
        $this->title         = 'Series Code';
        $this->controller    = $this;
        $this->module        = 'series_codes';
        $this->module_prefix = 'payrolls/admin/filemanagers';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $response = array(
            'module'        => $this->module,
            'module_prefix' => $this->module_prefix,
            'controller'    => $this->controller,
            'title'         => $this->title,
            'series'        => SeriesCode::orderBy('code','asc')->paginate(50),
        );

        return view($this->module_prefix.'.'.$this->module.'.index',$response);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $response = array(
            'module'        => $this->module,
            'module_prefix' => $this->module_prefix,
            'controller'    => $this->controller,
            'title'         => $this->title,
            'action'        => 'SeriesCodeController@store',
        );

        return view($this->module_prefix.'.'.$this->module.'.create',$response);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $series = SeriesCode::find(@$request->id);
        $message = 'Series Code Updated!';
        $status = true;
        if(empty($series)){

            $status = false;
            $this->validate($request,[
                'code' => 'required|unique:pms_series_codes',
                'description'
            ]);

            $message = 'Series Code Created!';
            $series = new SeriesCode;
            
        }

        
        $series->fill($request->all());

        if($status == true){
            $series->updated_by = Auth::id();
        }else{
            $series->created_by = Auth::id();
        }
        $series->save();

        return redirect()
            ->route('series_codes.edit',[
                'id' => $series->id
            ])->with('success',$message);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SeriesCode  $seriesCode
     * @return \Illuminate\Http\Response
     */
    public function show(SeriesCode $seriesCode)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SeriesCode  $seriesCode
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $series = SeriesCode::find($id);

        $response = array(
            'module'        => $this->module,
            'module_prefix' => $this->module_prefix,
            'controller'    => $this->controller,
            'title'         => $this->title,
            'series'        => $series,
        );

        return view($this->module_prefix.'.'.$this->module.'.edit',$response);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SeriesCode  $seriesCode
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SeriesCode  $seriesCode
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        SeriesCode::destroy($id);
        return redirect($this->module_prefix.'/series_codes')->with('success', 'Series code successfully deleted!');
    }
}

mwssro_prod/resources/views/payrolls/admin/filemanagers/series_codes/_form.blade.php
<form method="POST" action="{{ url($module_prefix.'/'.$module ) }}" id="form">

<input type="hidden" name="_token" value="{{ csrf_token() }}">
<input type="hidden" name="id" value="{{ @$series->id }}">
<div class="row">
	<div class="col-md-4">
		<div class="form-group">
			<label>Code</label>
			<input type="text" name="code" class="form-control form-control-sm" placeholder="Enter code" required value="{{ @$series->code }}">
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-4">
		<div class="form-group">
			<label>Description</label>
			<input type="text" name="description" class="form-control form-control-sm" placeholder="Enter description" required value="{{ @$series->description }}">
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-4 text-right">
		<div class="form-group">
			<button class="btn btn-sm btn-primary"><i class="fas fa-save"></i> Save</button>
		</div>
	</div>
</div>


</form>

mwssro_prod/resources/views/payrolls/admin/filemanagers/series_codes/create.blade.php
@extends('app-filemanager')

@section('filemanager-content')


<div class="panel panel-default">
	<div class="panel-heading">{!! $title !!}</div>
	<div class="panel-body">
		
		<div class="row p-4">
			<div class="col-md-12">
				@include('payrolls.admin.filemanagers.series_codes._form')
			</div>
		</div>

	</div>
</div>

@endsection

mwssro_prod/resources/views/payrolls/admin/filemanagers/series_codes/edit.blade.php
@extends('app-filemanager')

@section('filemanager-content')

<div class="panel panel-default">
	<div class="panel-heading">{!! $title !!}</div>
	<div class="panel-body">
		
		<div class="row p-4">
			<div class="col-md-12">
				@include('payrolls.admin.filemanagers.series_codes._form')
			</div>
		</div>

	</div>
</div>

@endsection

@section('js-logic2')

<script type="text/javascript">
	$(document).ready(function(){

		if(`{{ Session::get('success') }}` != ""){
			swal({  title: `{{ Session::get('success') }}`,
					text: '',
					type: "success",
					icon: 'success',
				});
		}

	})
</script>

@endsection

mwssro_prod/resources/views/payrolls/admin/filemanagers/series_codes/index.blade.php
@extends('app-filemanager')

@section('filemanager-content')

<div class="panel panel-default">
	<div class="panel-heading">{!! $title !!}</div>
	<div class="panel-body">

		<div class="row p-2">
			<div class="col-md-12">
				<a href="{{ route('series_codes.create') }}" class="btn btn-sm btn-primary"><i class="fas fa-plus"></i> Create</a>
			</div>
		</div>

		<div class="row p-4">
			<div class="col-md-12">
				<table class="table" id="table">
					<thead>
						<tr>
							<th>Code</th>
							<th>Description</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($series as $item)
						<tr>
							<td>{!! $item->code !!}</td>
							<td>{!! $item->description !!}</td>
							<td style="width: 20%;" class="text-center">
								<div class="row form-group">
									<div class="col-md-6">
										<a class="btn btn-xs btn-success" href="{{ route('series_codes.edit',['id' => $item->id]) }}"><i class="fa fa-edit"></i> Edit</a>
									</div>
									<div class="col-md-6">
										<form action="{{ url($module_prefix.'/series_codes/'.$item->id) }}" method="POST">
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<input type="hidden" name="_method" value="DELETE">
											<button type="submit" class="btn btn-xs btn-danger" onclick="return confirm('Delete record?')"><i class="fa fa-trash"></i> Delete</button>
										</form>
									</div>
								</div>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>

	</div>
</div>


@endsection

@section('js-logic2')
<script type="text/javascript">
	$(document).ready(function(){
		var table = $('#table').DataTable();

		if(`{{ Session::get('success') }}` != ""){
			swal({  title: `{{ Session::get('success') }}`,
					text: '',
					type: "success",
					icon: 'success',
				});
		}
	});
</script>

@endsection